sudo: required
services:
  - docker

before_install:
  - docker build --build-arg FONTAWESOME_NPM_AUTH_TOKEN=$FONTAWESOME_NPM_AUTH_TOKEN -t artemdemo/imgreview -f ./Dockerfile.dev .

script:
  - docker run -e FONTAWESOME_NPM_AUTH_TOKEN=$FONTAWESOME_NPM_AUTH_TOKEN artemdemo/imgreview npm run test:coverage
