sudo: required
services:
  - docker

before_install:
  - docker build --build-arg FONTAWESOME_NPM_AUTH_TOKEN=$FONTAWESOME_NPM_AUTH_TOKEN -t artemdemo/img-review -f ./Dockerfile.dev .

script:
  - docker run -e FONTAWESOME_NPM_AUTH_TOKEN=$FONTAWESOME_NPM_AUTH_TOKEN artemdemo/img-review npm run test:coverage
