export const CREATE_ARROW = 'CREATE_ARROW';
export const SET_IMAGE = 'SET_IMAGE';
export const EXPORT_CANVAS_TO_IMAGE = 'EXPORT_CANVAS_TO_IMAGE';
export const UPDATE_CANVAS_SIZE = 'UPDATE_CANVAS_SIZE';

export const ON_IMAGE_UPDATE = 'ON_IMAGE_UPDATE';
