@startuml
!include ./skin/clean.skin

class "MISave" as misave {
    Menu item
}

package "model/canvas" <<Frame>> {
  class "saveCanvas()" as saveCanvas {
      action
  }
  class "saveCanvas" as saveCanvasReducer {
      reducer
  }
  class "downloadURI" as downloadURI {
     function
  }
}

misave --right> saveCanvas
saveCanvas --> saveCanvasReducer
saveCanvasReducer --> downloadURI

@enduml
