export const CREATE_ARROW = 'CREATE_ARROW';
export const SET_IMAGE = 'SET_IMAGE';
export const SET_STROKE_COLOR_TO_ACTIVE_SHAPE = 'SET_STROKE_COLOR_TO_ACTIVE_SHAPE';
export const EXPORT_CANVAS_TO_IMAGE = 'EXPORT_CANVAS_TO_IMAGE';
export const UPDATE_CANVAS_SIZE = 'UPDATE_CANVAS_SIZE';
export const BLUR_SHAPES = 'BLUR_SHAPES';

export const ON_IMAGE_UPDATE = 'ON_IMAGE_UPDATE';
